services:
  - type: web
    name: active-learning-ner
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd api && python main_simple.py"
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"